### PR TITLE
test: add test for range request on multi block CAR

### PR DESCRIPTION
**Pull request by guanzo**
Handles https://github.com/filecoin-saturn/js-client/issues/49

I created a 1KB file with random bytes, added it to ipfs with chunk size 256B, then exported it to `multi_block.car`

Note the off-by-1 trickiness wrt byte ranges. 

If you want 25 bytes starting at byte 25, then the range config is `{ rangeStart: 25, rangeEnd: 49 }`

### CODE REVIEW

**Review by hannahhoward — CHANGES_REQUESTED** [review]
So yes, HTTP Range headers are bizarrely inclusive of the end of the range as well as the start, which makes reading N bytes extremely unintuitive. I decided to keep the range end inclusive at the JS Client level, but we could certainly push the conversion from inclusive to exclusive of the range end up to the service worker if you think that makes more sense.

Unfortunately, this isn't quite the test we're looking for yet. In the multiblock CAR file you've constructed, a proper car response would include ONLY the blocks that are part of the range. I think this still works cause you're reading a range in the first block. But if you shift your range to say 300-399 I think you will find this CAR file fails, as it should. I went ahead and made a CAR file with just the
[multi_block_filtered.car.zip](https://github.com/filecoin-saturn/js-client/files/13985268/multi_block_filtered.car.zip)
 header block and the block for bytes 256-512, if you want to use it:

**Comment by guanzo** [comment]
d'oh, good point. will fix

**Comment by guanzo** [comment]
Fixed. Decided to keep the `multi_block.car` fixture so we can derive the test's expected value.

**Review by hannahhoward — APPROVED** [review]
LGTM

**Review by AmeanAsad — APPROVED** [review]

**Pull request merged**
